### ISSUE TITLE
Ошибки

### ISSUE THREAD

**Issue by Mechnuna** [hashlyschool/42_minishell#27]
"cat < Makefile 222>1 ; rm 1" 
Your exit status : 0
Expected exit status : 1

**Comment by Mechnuna** [comment]
Бесконечный цикл при cat /dev/random | head -c 100 | wc -c

**Comment by Mechnuna** [comment]
Неправильно обрабатывает export A=a; echo $_

**Comment by Mechnuna** [comment]
[EXPORTS A='file'] echo bonjour > $A
Создает файл !{$A}!!

**Comment by hashlyschool** [comment]
> Неправильно обрабатывает export A=a; echo $_

А нижнее подчёркивания я не реализовывал. Не нашёл даже намёка в сабже по этому поводу
